INFO:root:127.0.0.1
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:root:2022-07-04 07:21:23.272892:127.0.0.1
ERROR:root:2022-07-04 07:21:50.906938:127.0.0.1:User1:Hash1
ERROR:root:2022-07-04 07:22:19.053655:127.0.0.1:User1:hash
ERROR:root:2022-07-04 07:21:50.906938:127.0.0.1:User1:Hash1
ERROR:root:2022-07-04 07:22:53.384715:127.0.0.1:User1:hash ERROR:root:2022-07-04 07:21:50.906938:127.0.0.1:User1:Hash1
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
ERROR:root:2022-07-04 07:33:40.803427:127.0.0.1:User1
ERROR:root:2022-07-04 07:33:56.077580:127.0.0.1:User1 \nuser2
INFO:root:2022-07-04 07:45:55.218505:127.0.0.1
INFO:root:2022-07-04 07:48:54.794168:127.0.0.1
INFO:root:2022-07-04 07:49:48.437612:127.0.0.1
INFO:root:2022-07-04 07:49:50.548011:127.0.0.1
INFO:root:2022-07-04 07:50:15.676492:127.0.0.1
INFO:root:2022-07-04 07:50:39.003232:127.0.0.1
INFO:root:2022-07-04 07:50:48.264349:127.0.0.1
INFO:root:2022-07-04 07:51:29.216251:127.0.0.1
INFO:root:2022-07-04 07:51:34.019034:127.0.0.1
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_lab2 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_lab2 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
WARNING:django.security.csrf:Forbidden (CSRF token from POST incorrect.): /ssrf_lab2
WARNING:django.request:Not Found: /favicon.ico
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_lab2 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.112.128:80
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.youtube.com:443
DEBUG:urllib3.connectionpool:https://www.youtube.com:443 "GET /watch?v=ynImA_neDfQ HTTP/1.1" 200 None
WARNING:django.request:Not Found: /s/player/0e7373c2/www-player.css
WARNING:django.request:Not Found: /s/player/0e7373c2/player_ias.vflset/en_GB/base.js
WARNING:django.request:Not Found: /s/player/0e7373c2/www-player.css
WARNING:django.request:Not Found: /s/search/audio/failure.mp3
WARNING:django.request:Not Found: /s/search/audio/open.mp3
WARNING:django.request:Not Found: /s/search/audio/no_input.mp3
WARNING:django.request:Not Found: /s/search/audio/success.mp3
WARNING:django.request:Not Found: /s/player/0e7373c2/player_ias.vflset/en_GB/base.js
WARNING:django.request:Not Found: /s/player/0e7373c2/www-player.css
WARNING:django.request:Not Found: /youtubei/v1/feedback
WARNING:django.request:Not Found: /youtubei/v1/next
WARNING:django.request:Not Found: /youtubei/v1/next
WARNING:django.request:Not Found: /youtubei/v1/guide
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): github.com:443
DEBUG:urllib3.connectionpool:https://github.com:443 "GET / HTTP/1.1" 200 None
WARNING:django.request:Not Found: /webgl-globe/data/data.json
WARNING:django.request:Not Found: /webgl-globe/images/map.png
WARNING:django.request:Not Found: /_graphql/GetSuggestedNavigationDestinations
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): github.com:443
DEBUG:urllib3.connectionpool:https://github.com:443 "GET / HTTP/1.1" 200 None
WARNING:django.request:Not Found: /webgl-globe/data/data.json
WARNING:django.request:Not Found: /webgl-globe/images/map.png
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /login/ HTTP/1.1" 200 17092
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 200 15294
WARNING:django.security.csrf:Forbidden (Origin checking failed - http://192.168.153.22 does not match any trusted origins.): /login/
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/pygoat/settings.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/pygoat/settings.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/pygoat/settings.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/pygoat/settings.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/pygoat/settings.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/pygoat/settings.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/pygoat/settings.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/pygoat/settings.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/pygoat/settings.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/pygoat/settings.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/pygoat/settings.py changed, reloading.
WARNING:django.request:Not Found: /target
WARNING:django.request:Not Found: /favicon.ico
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 200 15294
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /ssrf_target HTTP/1.1" 200 15294
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): github.com:443
DEBUG:urllib3.connectionpool:https://github.com:443 "GET /adeyosemanputra/pygoat HTTP/1.1" 200 None
WARNING:django.request:Not Found: /adeyosemanputra/pygoat/security/overall-count
WARNING:django.request:Not Found: /adeyosemanputra/pygoat/spoofed_commit_check/2ae4341d934e757ae10df7d3fba392547fcaac5b
WARNING:django.request:Not Found: /adeyosemanputra/pygoat/code_menu_contents/master
WARNING:django.request:Not Found: /adeyosemanputra/pygoat/hovercards/citation/sidebar_partial
WARNING:django.request:Not Found: /adeyosemanputra/pygoat/commit/2ae4341d934e757ae10df7d3fba392547fcaac5b/rollup
WARNING:django.request:Not Found: /adeyosemanputra/pygoat/overview_actions/master
WARNING:django.request:Not Found: /adeyosemanputra/pygoat/file-list/master
WARNING:django.request:Not Found: /adeyosemanputra/pygoat/used_by_list
WARNING:django.request:Not Found: /users/adeyosemanputra/hovercard
WARNING:django.request:Not Found: /users/adeyosemanputra/hovercard
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/views.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:root:2022-07-14 12:22:57.185086:127.0.0.1
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/main.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/main.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/main.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/main.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/main.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /2021/discussion/A9/target
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /2021/discussion/A9/target
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /2021/discussion/A9/target
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /2021/discussion/A9/target
WARNING:django.security.csrf:Forbidden (CSRF token missing.): /2021/discussion/A9/target
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/urls.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
ERROR:django.request:Internal Server Error: /2021/discussion/A9/api
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py", line 59, in log_function_checker
    lines = f.readlines()
io.UnsupportedOperation: not readable
ERROR:django.request:Internal Server Error: /2021/discussion/A9/api
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py", line 59, in log_function_checker
    lines = f.readlines()
io.UnsupportedOperation: not readable
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
ERROR:django.request:Internal Server Error: /2021/discussion/A9/api
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py", line 59, in log_function_checker
    lines = f.readlines()
io.UnsupportedOperation: not readable
ERROR:django.request:Internal Server Error: /2021/discussion/A9/api
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py", line 59, in log_function_checker
    lines = f.readlines()
io.UnsupportedOperation: not readable
ERROR:django.request:Internal Server Error: /2021/discussion/A9/api
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py", line 59, in log_function_checker
    lines = f.readlines()
io.UnsupportedOperation: not readable
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
ERROR:django.request:Internal Server Error: /2021/discussion/A9/api
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py", line 67, in log_function_checker
    requests.request("PATCH", url, payload=payload)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: Session.request() got an unexpected keyword argument 'payload'
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
ERROR:django.request:Internal Server Error: /2021/discussion/A9/api
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py", line 67, in log_function_checker
    requests.request("PATCH", url, payload=payload)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: Session.request() got an unexpected keyword argument 'payload'
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/main.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/main.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/main.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    password = request.POST['password']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77131
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77097
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
ERROR:django.request:Internal Server Error: /2021/discussion/A9/api
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py", line 59, in log_function_checker
    log_code = request.POST.get['log_code']
TypeError: 'method' object is not subscriptable
ERROR:django.request:Internal Server Error: /2021/discussion/A9/api
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py", line 59, in log_function_checker
    log_code = request.POST.get['log_code']
TypeError: 'method' object is not subscriptable
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /2021/discussion/A9/api
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py", line 59, in log_function_checker
    log_code = request.POST.get['log_code']
TypeError: 'method' object is not subscriptable
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 12, in log_function_target
    password = request.POST['password']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77131
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/main.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 11, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77087
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 11, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77087
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 11, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77087
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/main.py changed, reloading.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "GET /2021/discussion/A9/target HTTP/1.1" 200 50
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
ERROR:django.request:Internal Server Error: /2021/discussion/A9/target
Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py", line 11, in log_function_target
    username = request.POST['username']
  File "/home/rupak/Desktop/GSoC/pygoat/env/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "POST /2021/discussion/A9/target HTTP/1.1" 500 77087
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "PATCH /2021/discussion/A9/target HTTP/1.1" 200 41
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:8000
DEBUG:urllib3.connectionpool:http://127.0.0.1:8000 "DELETE /2021/discussion/A9/target HTTP/1.1" 200 52
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/playground/A9/api.py changed, reloading.
INFO:django.utils.autoreload:/home/rupak/Desktop/GSoC/pygoat/pygoat/introduction/apis.py changed, reloading.
